test

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -5,32 +5,83 @@ on:
   pull_request: 
 
 jobs:
+  sample-job0:  
+    runs-on: ubuntu-latest
+    steps:
+      - run: echo sometext0;
 
   sample-job:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout 
-        uses: actions/checkout@v3
+      - run: echo sometext; exit 1
+  # get-job:
+  #   if: always()
+  #   needs: [sample-job]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/github-script@v6
+  #       id: failed-job
+  #       with:
+  #         script: |
+  #            const results = await github.rest.actions.listJobsForWorkflowRun({
+  #               owner: context.repo.owner,
+  #               repo: context.repo.repo,
+  #               run_id: context.runId
+  #               });
+  #             results.data.jobs.forEach(job => {
+  #               if (job.conclusion === 'failure'){
+  #                 console.log(job.name)
+  #                 return job.name
+  #               }
+  #             })
+  # test-api: 
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - run: exit 1
 
-      - name: Cache Cypress Binary
-        id: cache-cypress-binary
-        uses: actions/cache@v2
+  slack-notify:
+    if: failure() && (github.ref_name == 'main' || github.base_ref == 'main')
+    runs-on: ubuntu-latest
+    needs: [sample-job]
+    steps:
+      - name: Get failed job 
+        uses: actions/github-script@v6
+        id: failed-job
         with:
-          path: .cache/cypress
-          key: cypress-binary-${{ hashFiles('package-lock.json') }}
+          result-encoding: string
+          script: |
+             const results = await github.rest.actions.listJobsForWorkflowRun({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                run_id: context.runId
+                });
+              for (let job of results.data.jobs){
+                if (job.conclusion === 'failure'){
+                    return job.name
+                }
+              }
+      - run: echo ${{steps.failed-job.outputs.result}}
+      - name: action-slack
+        uses: 8398a7/action-slack@v3.12.0
+        with:
+          mention: ${{fromJSON(env.users)[github.actor]}} 
+          if_mention: always
+          text: "Check Github Actions"
+          author_name: ${{github.job}}
+          status: failure
+          job_name: ${{steps.failed-job.outputs.result}}
+          fields: commit, message, job, ref
           
-      - name: Get npm cache directory
-        id: npm-cache-dir
-        run: |
-          echo "::set-output name=dir::$(npm config get cache)"
-      - uses: actions/cache@v3
-        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
-        with:
-          path: ${{ steps.npm-cache-dir.outputs.dir }}
-          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
-      
-      - name: Install time
-        run: npm install --prefer-offline --no-audit --no-fund
-
-      - name: ci
-        run: npm ci
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+          users: >- 
+            '{
+              "elofstead": "U03JEDFJ8HG",
+              "Emmanuel-Mekonnen": "U038C3ZQLHF",
+              "esudaley": "U037SRG0Y5C",
+              "JCWheaton": "U016Z3721A5",
+              "jharris711": "U018R01JA0G",
+              "maxlliiw": "U02214HK3RQ",
+              "sethheidelberg": "U035KN45YSV",
+              "stevemarin": "U016M0CTMR9"
+            }'
